### PR TITLE
Fix responsive on small screens

### PR DESCRIPTION
**Pull request by musartedev**
image

With ♥︎ to Oscar Barajas Jr.

### CODE REVIEW

**Comment by iosamuel** [comment]
It's not needed to remove the cart image, you could just add an `overflow: auto` property to `div. App` and it will fix the background behind 😊

**Comment by iosamuel** [comment]
Although it looks good, haha. Decision is up to @gndx

**Comment by musartedev** [comment]
> It's not needed to remove the cart image, you could just add an `overflow: auto` property to `div. App` and it will fix the background behind 😊

Thanks!! It was more a visual decision, I personally think it makes no sense to have two figures on small screens and scroll just to see the second one.

**Comment by iosamuel** [comment]
> > It's not needed to remove the cart image, you could just add an `overflow: auto` property to `div. App` and it will fix the background behind 😊
> 
> Thanks!! It was more a visual decision, I personally think it makes no sense to have two figures on small screens and scroll just to see the second one.

Yeah, I actually like it!

**Pull request merged**
